#!/usr/bin/env bash
# Creates or updates frontend/.env.local for local development WITHOUT Google OAuth.
# Usage:
#   ./setup-local-env.sh              Create .env.local (fails if file exists)
#   ./setup-local-env.sh --force      Backup existing .env.local, then create fresh
#   ./setup-local-env.sh --merge      Keep existing file; append missing localhost vars only

set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

write_fresh() {
  local secret
  secret="$(openssl rand -base64 32)"
  cat > .env.local << EOF
# Generated by setup-local-env.sh — local dev without Google (do not use in production)
NEXT_PUBLIC_API_URL=http://localhost:8000

NEXT_PUBLIC_SKIP_AUTH=true
NEXTAUTH_SECRET=${secret}
NEXTAUTH_URL=http://localhost:3000

# Google OAuth (optional — uncomment and fill when you want real sign-in)
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
EOF
  echo "Wrote frontend/.env.local with NEXT_PUBLIC_SKIP_AUTH=true and a generated NEXTAUTH_SECRET."
}

merge_missing() {
  local f=".env.local"
  local changed=0
  append_if_missing() {
    local key="$1"
    local val="$2"
    if grep -qE "^[[:space:]]*${key}=" "$f" 2>/dev/null; then
      return 0
    fi
    echo "${key}=${val}" >> "$f"
    echo "  + Added ${key}"
    changed=1
  }
  touch "$f"
  append_if_missing "NEXT_PUBLIC_API_URL" "http://localhost:8000"
  append_if_missing "NEXT_PUBLIC_SKIP_AUTH" "true"
  if ! grep -qE "^[[:space:]]*NEXTAUTH_SECRET=" "$f" 2>/dev/null; then
    echo "NEXTAUTH_SECRET=$(openssl rand -base64 32)" >> "$f"
    echo "  + Added NEXTAUTH_SECRET"
    changed=1
  fi
  append_if_missing "NEXTAUTH_URL" "http://localhost:3000"
  if [[ "$changed" -eq 0 ]]; then
    echo "No missing keys — .env.local already had localhost dev settings."
  else
    echo "Updated .env.local (existing lines kept)."
  fi
}

if [[ -f .env.local ]]; then
  case "${1:-}" in
    --force)
      bak=".env.local.bak.$(date +%Y%m%d%H%M%S)"
      cp .env.local "$bak"
      echo "Backed up existing file to $bak"
      write_fresh
      ;;
    --merge)
      merge_missing
      ;;
    *)
      echo "frontend/.env.local already exists."
      echo ""
      echo "Choose one:"
      echo "  ./setup-local-env.sh --force   Backup current file, then write a fresh localhost dev .env.local"
      echo "  ./setup-local-env.sh --merge   Keep your file; only add missing NEXT_PUBLIC_* / NEXTAUTH_* lines"
      echo ""
      echo "Or edit .env.local by hand and ensure you have:"
      echo "  NEXT_PUBLIC_API_URL=http://localhost:8000"
      echo "  NEXT_PUBLIC_SKIP_AUTH=true"
      echo "  NEXTAUTH_SECRET=<run: openssl rand -base64 32>"
      echo "  NEXTAUTH_URL=http://localhost:3000"
      exit 1
      ;;
  esac
else
  write_fresh
fi

echo "Restart the dev server: npm run dev"
echo "Then open http://localhost:3000"
