#!/usr/bin/env bash
# Creates frontend/.env.local for local development WITHOUT Google OAuth.
# For production Google sign-in, copy .env.local.example and fill in OAuth credentials.

set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

if [[ -f .env.local ]]; then
  echo "frontend/.env.local already exists."
  echo "Delete or rename it first, or edit it by hand and add:"
  echo "  NEXT_PUBLIC_SKIP_AUTH=true"
  echo "  NEXTAUTH_SECRET=\$(openssl rand -base64 32)"
  echo "  NEXTAUTH_URL=http://localhost:3000"
  exit 1
fi

SECRET="$(openssl rand -base64 32)"

cat > .env.local << EOF
# Generated by setup-local-env.sh — local dev without Google (do not use in production)
NEXT_PUBLIC_API_URL=http://localhost:8000

NEXT_PUBLIC_SKIP_AUTH=true
NEXTAUTH_SECRET=${SECRET}
NEXTAUTH_URL=http://localhost:3000

# Google OAuth (optional — uncomment and fill when you want real sign-in)
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
EOF

echo "Created frontend/.env.local with NEXT_PUBLIC_SKIP_AUTH=true and a generated NEXTAUTH_SECRET."
echo "Restart the dev server: npm run dev"
echo "Then open http://localhost:3000 — no Google sign-in required."
